### ISSUE TITLE
Add travis-ci support!

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/DotFiles#44]
I want to add travis-ci support for my dotfiles, how could I implement it?
.travis.yml
```yml
language: viml

sudo: required
dist: trusty

os:
    - linux
    - osx
osx_image: xcode7.3

before_script:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install vim --HEAD; fi
    - vim --version
    - git clone https://github.com/syngan/vim-vimlint /tmp/vim-vimlint
    - git clone https://github.com/ynkdir/vim-vimlparser /tmp/vim-vimlparser
    - git clone https://github.com/thinca/vim-themis

script:
    - sh /tmp/vim-vimlint/bin/vimlint.sh -l /tmp/vim-vimlint -p /tmp/vim-vimlparser -e EVL103=1 -e EVL102.l:_=1 autoload
    - vim-themis/bin/themis --reporter spec
```

another

```yml
language: python

cache:
  pip: true
  directories:
    - /tmp/vimlint
    - /tmp/vimlparser
    - /tmp/vint

# Don't reinstall dependencies if they have been cached
install:
  - '[ -d /tmp/vimlint ] || git clone https://github.com/syngan/vim-vimlint /tmp/vimlint'
  - '[ -d /tmp/vimlparser ] || git clone https://github.com/ynkdir/vim-vimlparser /tmp/vimlparser'
  - '[ -d /tmp/vint/bin ] || virtualenv /tmp/vint && source /tmp/vint/bin/activate'
  - 'vint --version || pip install vim-vint'

script:
  - sh /tmp/vimlint/bin/vimlint.sh -l /tmp/vimlint -p /tmp/vimlparser -v $TRAVIS_BUILD_DIR
  - vint --error $TRAVIS_BUILD_DIR
```
